/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gwgwbmibvvcxuttndfkn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3Z3dibWlidnZjeHV0dG5kZmtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2ODkyNTQsImV4cCI6MjA4MDI2NTI1NH0.0IMfDgw-kZgt9aWXaPkKgJ6LM5q1oDoaZ6-Wk0Ypw1U"